### ISSUE TITLE
Issue capturing downlink packets

### ISSUE THREAD

**Issue by Iblist** [SysSec-KAIST/LTESniffer#27]
Hi, I'm trying to sniff downlink traffic using a HackRF One. It looks like subframes are being processed, but I'm not seeing any packets being captured and ltesniffer_dl_mode.pcap is empty. I'm wondering if this is a hardware limitation of the HackRF One or if there could be a different issue like low signal level or a botched install. Thanks for the help!
Output is as follows;

sudo ./LTESniffer -W 4 -f 753.5e6 -I 408 -m 0
...
[09:03:51] Processed 1000/1000 subframes
[09:03:52] Processed 1000/1000 subframes
[09:03:53] Processed 1000/1000 subframes
[09:03:54] Processed 1000/1000 subframes
^CLTESniffer_Core: Exiting...
\-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    \-------------------------------------------------------------------------------------------------------------
\-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    
\-------------------------------------------------------------------------------------------------------------
[256Tracking] Total: 0 RNTIs are 64QAM table, 0 RNTIs are 256QAM table, 0 RNTIs are Unknown 

Destroyed Phy
Skipped subframe: 0 / 38376
nof_decoded_locations, nof_cce, nof_missed_cce, nof_subframes, nof_subframe_collisions_dw, nof_subframe_collisions_up, time, nof_locations
0, 0, 0, 0, 0, 0, 0.000000, 0
Skipped subframes: 0 (-nan%)
Saving MAC PCAP file
Deleted DL Sniffer core
...

**Comment by Iblist** [comment]
Update, it turns out I didn't have enough receive signal. I used an amplifier to increase the signal strength and now I'm capturing packets.

**Comment by arifkyi** [comment]
Hello, This post issue is help and and convince me that HackRf is no issue right for downlink only supposedly?

so i do not need to buy the bladeRf or others more expensive stuff right?  after you buy the amplifier then works charmly right Sir ?
