### ISSUE TITLE
Problem about 10Gb card to connect USRP X310 to PC

### ISSUE THREAD

**Issue by Rensiyi** [SysSec-KAIST/LTESniffer#30]
Hi, I'm trying LTESniffer for general uplink sniffing. I have a question about connecting USRP X310 to PC. Is it possible to replace the 10Gb card with a 1Gb card. Thank you very much.

**Comment by hdtuanss** [comment]
Hi. Sorry I'm not sure about it, I don't have 1 Gb card to test.
