### ISSUE TITLE
Downlink/uplink::Bad_allocation

### ISSUE THREAD

**Issue by RSS06** [SysSec-KAIST/LTESniffer#36]
Hello,

I have tried downlink and uplink sniffer. it ends up with------------>

**For Downlink-**-------->

**sudo /home/ql/LTESniffer/build/src/LTESniffer -A 2 -W 4 -f 18294e5 -C -m 0**

LTESniffer

Thu_Aug_24_16.41.13_2023.
Creating Phy
Creating 4 Worker threads 

Opening RF device with 2 RX antennas...
Available RF device list: UHD 
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-265-ga2a04e31
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=2, args: type=x300,master_clock_rate=184.32e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [GPS] Found an internal GPSDO: LC_XO, Firmware Rev 0.929a
[WARNING] [GPS] update_cache(): Malformed GPSDO string: LC_XO, Firmware Rev 0.929a
[INFO] [X300] Radio 1x clock: 184.32 MHz
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[INFO] [MULTI_USRP]     1) catch time transition at pps edge
[INFO] [MULTI_USRP]     2) set times next pps (synchronously)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
RF device 'UHD' successfully opened
Starting AGC thread...
Tunning receiver to 1829.400 MHz
Searching for cell...
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
*Found Cell_id: 434 FDD, CP: Normal  , DetectRatio=100% PSR=3.38, Power=-53.7 dBm
Decoding PBCH for cell 434 (N_id_2=2)
[ERROR] [UHD RF] std::bad_alloc
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_uhd_imp.cc:1340: Error timed out while receiving samples from UHD.
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_mib.c:256: Error calling srsran_ue_sync_work()
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:138: Error decoding MIB
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:263: Could not decode PBCH from CELL ID 434
/home/ql/LTESniffer/src/src/LTESniffer_Core.cc:199: Error searching for cell
terminate called without an active exception
Aborted

**For Uplink**----------->

s**udo /home/ql/LTESniffer/build/src/LTESniffer -A 2 -W 4 -f 18294e5 -u 1740e6 -C -m 1** 

LTESniffer

Thu_Aug_24_16.54.36_2023.
Creating Phy
Creating 4 Worker threads 
Opening RF device with 2 RX antennas...
Available RF device list: UHD 
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-265-ga2a04e31
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=2, args: type=x300,master_clock_rate=184.32e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [GPS] Found an internal GPSDO: LC_XO, Firmware Rev 0.929a
[INFO] [X300] Radio 1x clock: 184.32 MHz
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[INFO] [MULTI_USRP]     1) catch time transition at pps edge
[INFO] [MULTI_USRP]     2) set times next pps (synchronously)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24912805 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24912805
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
RF device 'UHD' successfully opened
Starting AGC thread...
Tunning DL receiver to 1829.400 MHz
Tunning UL receiver to 1740.000 MHz
Searching for cell...
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
*Found Cell_id: 434 FDD, CP: Normal  , DetectRatio=100% PSR=4.31, Power=-59.4 dBm
Decoding PBCH for cell 434 (N_id_2=2)
[ERROR] [UHD RF] std::bad_alloc
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_uhd_imp.cc:1340: Error timed out while receiving samples from UHD.
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_mib.c:256: Error calling srsran_ue_sync_work()
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:138: Error decoding MIB
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:263: Could not decode PBCH from CELL ID 434
/home/ql/LTESniffer/src/src/LTESniffer_Core.cc:199: Error searching for cell
terminate called without an active exception
Aborted

**Comment by RSS06** [comment]
Hello,

I have tried both--->
Still giving same error. Please have a look.


***@***.***:~$ sudo sysctl -w net.core.wmem_max=24912805
net.core.wmem_max = 24912805
***@***.***:~$ sudo sysctl -w net.core.rmem_max=24912805
net.core.rmem_max = 24912805
***@***.***:~$ sudo /home/ql/LTESniffer/build/src/LTESniffer -A 2 -W 4 -f 18294e5 -C -m 0

LTESniffer

Thu_Aug_24_17.06.48_2023.
Creating Phy
Creating 4 Worker threads
Opening RF device with 2 RX antennas...
Available RF device list: UHD
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-265-ga2a04e31
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=2, args: type=x300,master_clock_rate=184.32e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [GPS] Found an internal GPSDO: LC_XO, Firmware Rev 0.929a
[INFO] [X300] Radio 1x clock: 184.32 MHz
[INFO] [MULTI_USRP]     1) catch time transition at pps edge
[INFO] [MULTI_USRP]     2) set times next pps (synchronously)
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#1] Attempting to set tick rate to 0. Skipping.
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
RF device 'UHD' successfully opened
Starting AGC thread...
Tunning receiver to 1829.400 MHz
Searching for cell...
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
 Found Cell_id:   0 FDD, CP: Normal  , DetectRatio= 0% PSR=0.00, Power=-inf dBm
*Found Cell_id: 434 FDD, CP: Normal  , DetectRatio=100% PSR=3.69, Power=-61.1 dBm
Decoding PBCH for cell 434 (N_id_2=2)
[ERROR] [UHD RF] std::bad_alloc
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_uhd_imp.cc:1340: Error timed out while receiving samples from UHD.
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/ue/ue_mib.c:256: Error calling srsran_ue_sync_work()
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:138: Error decoding MIB
/home/ql/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:263: Could not decode PBCH from CELL ID 434
/home/ql/LTESniffer/src/src/LTESniffer_Core.cc:199: Error searching for cell
terminate called without an active exception
Aborted




________________________________

**Comment by hdtuanss** [comment]
Could you check whether USRP X310 is connected to PC via 10G card? please execute `uhd_usrp_probe` and `ifconfig` and see the result

**Comment by jrpowe27** [comment]
I'm glad to see that I am not alone. I, too, got the exact same error/output when running my setup. I also tried adjusting the memory settings to no avail after verifying that the USRP X310 was connected to PC via 10G card. The firmware version loaded on the X310 is UHD 4.4.0.0-124-g8a670958.

**Comment by alphafox02** [comment]
I'm using UHD 4.1.0.5 (22.04) w/ X310 connected via 10G card and do not have this issue. The X310 is also connected to a PC w/ i7 and 32GB ram. Maybe worth trying another UHD version?

**Comment by hdtuanss** [comment]
Hi, I'm testing this error. It seems there is an incompatibility between UHD and srsRAN library. It showed the same error when running pdsch_ue example from srsRAN lib. I will report the result later. Thanks

**Comment by hdtuanss** [comment]
Hi all, if you have problem with std::bad_alloc, please try Ubuntu 18.04 and UHD 4.0 together, that tips will help you solve the problem. I still dont know exactly why std::bad_alloc happens, it seems there is an incompatibility between UHD, Ubuntu version, and srsRAN library

**Comment by alphafox02** [comment]
If you also want to quickly see if it’s the particular software combination as suggested, grab the latest DragonOS FocalX which I’ve tested using my x310. You can download, boot, and try it live from USB as LTESniffer is already included. I ran it again just yesterday while testing against srsRan. Maybe this will also help isolate the problem.

**Comment by jrpowe27** [comment]
Thank you for investigating.

**Comment by RSS06** [comment]
Hello,

Is it possible to get following using LTESniffer-

   1. the time advance value for each uplink subframe in nanosecond value.
    2. can we convert the time we are receiving in .pcap file into nanosecond.
    3. Like Airscope, is it possible to capture the IQ data from USRP and decode it later. For ex. Airscope uses usrp_capture_sync tool to capture IQ data and decode later by providing the path for stored data.
