### ISSUE TITLE
No Pcap were saved

### ISSUE THREAD

**Issue by arifkyi** [SysSec-KAIST/LTESniffer#39]
Hello Need your kindly help

Im using this command:

$ sudo LTESniffer -A 1 -W 6 -f 1832500000 -I 332 -p 15 -m 0

and can get the RNTI where fetched like below and you can see one of them were 100% success

My quesrtion after i stopped, the PCAP is always empty:
-rw-r--r-- 1 root  root      2022 Sep 22 15:56 mcs_statistic.csv
-rw-r--r-- 1 root  root        24 Sep 22 15:56 **ltesniffer_dl_mode**.pcap

Need your kindly help for resolution ?

^C-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    
-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    
1    1        Unknown     1        1        0        0(0%)        0        0        0        0        0        
2    10       Unknown     1        1        0        0(0%)        0        0        0        0        0        
3    9057     Unknown     1        1        0        0(0%)        0        0        0        0        0        
4    11117    Unknown     2        2        0        0(0%)        0        0        0        0        0        
5    20131    Unknown     2        2        0        0(0%)        0        0        0        0        0        
**6    20448    Unknown     1        1        0        1(100%)      0        0        0        0        0**        
7    26961    Unknown     2        2        0        0(0%)        0        0        0        0        0        
8    45898    Unknown     1        1        0        0(0%)        0        0        0        0        0        
-------------------------------------------------------------------------------------------------------------
[256Tracking] Total: 0 RNTIs are 64QAM table, 0 RNTIs are 256QAM table, **8 RNTIs are Unknown**

**Comment by hdtuanss** [comment]
HI, it seems no downlink packet was successfully decoded. Could you run LTESniffer for a longer time and add `-d` to your command too print out the debug message?
`sudo LTESniffer -A 1 -W 6 -f 1832500000 -I 332 -p 15 -m 0 -d`
Also, please check again number of PRB (15 in your command) of the listening cell, or using -C option to find all available cells.
`sudo LTESniffer -A 1 -W 6 -f 1832500000 -C -m 0 -d`
Thanks.

**Comment by arifkyi** [comment]
Hello Hdtuanss,

Thank you sooooo much for your response, 

anyway everytime i tried the -C command in my HackRF 
**sudo LTESniffer -A 1 -W 6 -f 1832500000 -C -m 0**
<quote>
it's alway like this, it wont stop if i dont type the ctrl+c :
/usr/src/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:207: Could not find any cell in this frequency
Cell not found after 299 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
/usr/src/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:207: Could not find any cell in this frequency
Cell not found after 300 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
/usr/src/LTESniffer/build/srsRAN-src/lib/src/phy/rf/rf_utils.c:207: Could not find any cell in this frequency
Cell not found after 301 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
<quote>
of course the frequency and port is exist right otherwise i wont get any RNTI like tha table that i already show it to you.

Let me do the -d and will get back to you

**Comment by arifkyi** [comment]
Hello 
the result of -d , i noticed some how intermittent saved not saved pcap
sudo LTESniffer -A 1 -W 6 -f 1832500000 -I 332 -p 15 -m 0  -d

nkown64 SF:668 -9 -- RNTI: 2812  -- DCI: 1    -- Mod: 16QAM  -- MCS: 16  -- nof_TB: 1 -- Byte: 193   -- Antenna SNR: 6.42|0    -- SNR: 6.59  -- Result:    FAILED
Unkown256SF:668 -9 -- RNTI: 2812  -- DCI: 1    -- Mod: 64QAM  -- MCS: 16  -- nof_TB: 1 -- Byte: 309   -- Antenna SNR: 6.42|0    -- SNR: 6.59  -- Result:    FAILED
[15:37:21] Processed 789/1000 subframes
[15:37:22] Processed 788/1000 subframes
[15:37:23] Processed 874/1000 subframes
[15:37:24] Processed 887/1000 subframes
Unkown64 SF:89  -9 -- RNTI: 11776 -- DCI: 1    -- Mod: QPSK   -- MCS: 1   -- nof_TB: 1 -- Byte: 28    -- Antenna SNR: 6.35|0    -- SNR: 6.81  -- Result:    FAILED
Unkown256SF:89  -9 -- RNTI: 11776 -- DCI: 1    -- Mod: QPSK   -- MCS: 1   -- nof_TB: 1 -- Byte: 37    -- Antenna SNR: 6.35|0    -- SNR: 6.81  -- Result:    FAILED
[15:37:25] Processed 825/1000 subframes
Unkown64 SF:190 -7 -- RNTI: 35534 -- DCI: 1    -- Mod: 16QAM  -- MCS: 12  -- nof_TB: 1 -- Byte: 73    -- Antenna SNR: 5.44|0    -- SNR: 6.46  -- Result:    FAILED
Unkown256SF:190 -7 -- RNTI: 35534 -- DCI: 1    -- Mod: 64QAM  -- MCS: 12  -- nof_TB: 1 -- Byte: 133   -- Antenna SNR: 5.44|0    -- SNR: 6.46  -- Result:    FAILED
[15:37:26] Processed 759/1000 subframes
Unkown64 SF:249 -6 -- RNTI: 58829 -- DCI: 1    -- Mod: 64QAM  -- MCS: 28  -- nof_TB: 1 -- Byte: 277   -- Antenna SNR: 6.18|0    -- SNR: 7.27  -- Result:    FAILED
Unkown256SF:249 -6 -- RNTI: 58829 -- DCI: 1    -- Mod: QPSK   -- MCS: 28  -- nof_TB: 1 -- Byte: 0     -- Antenna SNR: 6.18|0    -- SNR: 7.27  -- Result:    SUCCESS
Unkown64 SF:267 -1 -- RNTI: 13683 -- DCI: 1    -- Mod: QPSK   -- MCS: 1   -- nof_TB: 1 -- Byte: 41    -- Antenna SNR: 6.38|0    -- SNR: 6.45  -- Result:    FAILED
Unkown256SF:267 -1 -- RNTI: 13683 -- DCI: 1    -- Mod: QPSK   -- MCS: 1   -- nof_TB: 1 -- Byte: 47    -- Antenna SNR: 6.38|0    -- SNR: 6.45  -- Result:    FAILED
[15:37:27] Processed 728/1000 subframes
Unkown64 SF:295 -6 -- RNTI: 45733 -- DCI: 1    -- Mod: 64QAM  -- MCS: 25  -- nof_TB: 1 -- Byte: 717   -- Antenna SNR: 5.53|0    -- SNR: 6.38  -- Result:    FAILED
Unkown256SF:295 -6 -- RNTI: 45733 -- DCI: 1    -- Mod: 256QAM -- MCS: 25  -- nof_TB: 1 -- Byte: 1031  -- Antenna SNR: 5.53|0    -- SNR: 6.38  -- Result:    FAILED
64       SF:334 -3 -- RNTI: 32921 -- DCI: 1A   -- Mod: 64QAM  -- MCS: 18  -- nof_TB: 1 -- Byte: 485   -- Antenna SNR: 7.65|0    -- SNR: 8.19  -- Result:    FAILED
Unkown64 SF:338 -8 -- RNTI: 26617 -- DCI: 1    -- Mod: 64QAM  -- MCS: 25  -- nof_TB: 1 -- Byte: 69    -- Antenna SNR: 6.4 |0    -- SNR: 6.92  -- Result:    FAILED
Unkown256SF:338 -8 -- RNTI: 26617 -- DCI: 1    -- Mod: 256QAM -- MCS: 25  -- nof_TB: 1 -- Byte: 101   -- Antenna SNR: 6.4 |0    -- SNR: 6.92  -- Result:    FAILED
[15:37:28] Processed 744/1000 subframes
Unkown64 SF:411 -5 -- RNTI: 4343  -- DCI: 1    -- Mod: 64QAM  -- MCS: 21  -- nof_TB: 1 -- Byte: 485   -- Antenna SNR: 5.36|0    -- SNR: 6.04  -- Result:    FAILED
Unkown256SF:411 -5 -- RNTI: 4343  -- DCI: 1    -- Mod: 256QAM -- MCS: 21  -- nof_TB: 1 -- Byte: 749   -- Antenna SNR: 5.36|0    -- SNR: 6.04  -- Result:    FAILED
[15:37:29] Processed 858/1000 subframes
Unkown64 SF:535 -4 -- RNTI: 3016  -- DCI: 1    -- Mod: QPSK   -- MCS: 8   -- nof_TB: 1 -- Byte: 49    -- Antenna SNR: 5.4 |0    -- SNR: 6.09  -- Result:    FAILED
Unkown256SF:535 -4 -- RNTI: 3016  -- DCI: 1    -- Mod: 16QAM  -- MCS: 8   -- nof_TB: 1 -- Byte: 93    -- Antenna SNR: 5.4 |0    -- SNR: 6.09  -- Result:    FAILED
64       SF:556 -5 -- RNTI: 30152 -- DCI: 1A   -- Mod: QPSK   -- MCS: 8   -- nof_TB: 1 -- Byte: 67    -- Antenna SNR: 5.86|0    -- SNR: 6.9   -- Result:    FAILED
[15:37:30] Processed 750/1000 subframes
--------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success  HARQ     Normal   W_MIMO   W_pinfor Other    
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success  HARQ     Normal   W_MIMO   W_pinfor Other    
1    2812     Unknown     1        1        0        0        0        0        0        0        0        
2    3016     Unknown     1        1        0        0        0        0        0        0        0        
3    4311     Unknown     1        1        0        0        0        0        0        0        0        
4    4343     Unknown     1        1        0        0        0        0        0        0        0        
5    11776    Unknown     2        2        0        0        0        0        0        0        0        
6    12363    Unknown     1        1        0        0        0        0        0        0        0        
7    13683    Unknown     2        2        0        0        0        0        0        0        0        
8    16343    Unknown     1        1        0        0        0        0        0        0        0        
9    16389    Unknown     1        1        0        0        0        0        0        0        0        
10   17596    Unknown     2        2        0        0        0        0        0        0        0        
11   17920    Unknown     1        1        0        0        0        0        0        0        0        
12   19255    Unknown     1        1        0        0        0        0        0        0        0        
13   20063    Unknown     1        1        0        0        0        0        0        0        0        
14   20746    Unknown     1        1        0        0        0        0        0        0        0        
15   21637    Unknown     1        1        0        0        0        0        0        0        0        
16   26617    Unknown     1        1        0        0        0        0        0        0        0        
17   28999    Unknown     1        1        0        0        0        0        0        0        0        
18   30152    Unknown     1        1        0        0        0        0        0        0        0        
19   31184    Unknown     5        5        0        0        0        0        0        0        0        
20   32921    Unknown     1        1        0        0        0        0        0        0        0        
21   34435    Unknown     1        1        0        0        0        0        0        0        0        
22   35534    Unknown     1        1        0        0        0        0        0        0        0        
23   36144    Unknown     3        3        0        0        0        0        0        0        0        
24   36551    Unknown     1        1        0        0        0        0        0        0        0        
25   36868    Unknown     4        4        0        0        0        0        0        0        0        
26   39050    Unknown     3        3        0        1        0        0        0        0        0        
27   40950    Unknown     2        2        0        0        0        0        0        0        0        
28   43896    Unknown     1        1        0        0        0        0        0        0        0        
29   45733    Unknown     2        2        0        0        0        0        0        0        0        
30   50778    Unknown     1        1        0        0        0        0        0        0        0        
31   51147    Unknown     1        1        0        0        0        0        0        0        0        
32   52145    Unknown     1        1        0        0        0        0        0        0        0        
33   58829    Unknown     1        1        0        1        0        0        0        0        0        
34   63534    Unknown     1        1        0        0        0        0        0        0        0        
--------------------------------------------------------------------------------------------------------
[256Tracking] Total: 0 RNTIs are 64QAM table, 0 RNTIs are 256QAM table, 34 RNTIs are Unknown 


15:37:31] Processed 842/1000 subframes
[15:37:32] Processed 839/1000 subframes
Unkown64 SF:808 -8 -- RNTI: 34172 -- DCI: 1    -- Mod: 64QAM  -- MCS: 19  -- nof_TB: 1 -- Byte: 225   -- Antenna SNR: 6.3 |0    -- SNR: 6.72  -- Result:    FAILED
Unkown256SF:808 -8 -- RNTI: 34172 -- DCI: 1    -- Mod: 64QAM  -- MCS: 19  -- nof_TB: 1 -- Byte: 373   -- Antenna SNR: 6.3 |0    -- SNR: 6.72  -- Result:    FAILED
Unkown64 SF:890 -5 -- RNTI: 52247 -- DCI: 1    -- Mod: QPSK   -- MCS: 8   -- nof_TB: 1 -- Byte: 101   -- Antenna SNR: 6.38|0    -- SNR: 7.39  -- Result:    FAILED
Unkown256SF:890 -5 -- RNTI: 52247 -- DCI: 1    -- Mod: 16QAM  -- MCS: 8   -- nof_TB: 1 -- Byte: 193   -- Antenna SNR: 6.38|0    -- SNR: 7.39  -- Result:    FAILED
[15:37:33] Processed 798/1000 subframes
[15:37:34] Processed 742/1000 subframes
Unkown64 SF:18  -5 -- RNTI: 53835 -- DCI: 1    -- Mod: 64QAM  -- MCS: 24  -- nof_TB: 1 -- Byte: 201   -- Antenna SNR: 5.65|0    -- SNR: 6.87  -- Result:    FAILED
Unkown256SF:18  -5 -- RNTI: 53835 -- DCI: 1    -- Mod: 256QAM -- MCS: 24  -- nof_TB: 1 -- Byte: 293   -- Antenna SNR: 5.65|0    -- SNR: 6.87  -- Result:    FAILED
Unkown64 SF:43  -9 -- RNTI: 52633 -- DCI: 1    -- Mod: QPSK   -- MCS: 7   -- nof_TB: 1 -- Byte: 41    -- Antenna SNR: 6.14|0    -- SNR: 7.05  -- Result:    FAILED
Unkown256SF:43  -9 -- RNTI: 52633 -- DCI: 1    -- Mod: 16QAM  -- MCS: 7   -- nof_TB: 1 -- Byte: 85    -- Antenna SNR: 6.14|0    -- SNR: 7.05  -- Result:    FAILED
[15:37:35] Processed 804/1000 subframes
[15:37:36] Processed 866/1000 subframes
[15:37:37] Processed 715/1000 subframes
Unkown64 SF:365 -9 -- RNTI: 22776 -- DCI: 1    -- Mod: 16QAM  -- MCS: 15  -- nof_TB: 1 -- Byte: 105   -- Antenna SNR: 6.85|0    -- SNR: 7.53  -- Result:    FAILED
Unkown256SF:365 -9 -- RNTI: 22776 -- DCI: 1    -- Mod: 64QAM  -- MCS: 15  -- nof_TB: 1 -- Byte: 173   -- Antenna SNR: 6.85|0    -- SNR: 7.53  -- Result:    FAILED
[15:37:38] Processed 728/1000 subframes
64       SF:420 -2 -- RNTI: 19283 -- DCI: 1A   -- Mod: 64QAM  -- MCS: 23  -- nof_TB: 1 -- Byte: 749   -- Antenna SNR: 5.73|0    -- SNR: 6.68  -- Result:    FAILED
LTESniffer_Core: Exiting...
^C-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    
-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
Num  RNTI     Table       Active   New TX   ReTX     Success      HARQ     Normal   W_MIMO   W_pinfor Other    
1    2225     Unknown     1        1        0        0(0%)        0        0        0        0        0        
2    2812     Unknown     1        1        0        0(0%)        0        0        0        0        0        
3    3016     Unknown     1        1        0        0(0%)        0        0        0        0        0        
4    5111     Unknown     2        2        0        0(0%)        0        0        0        0        0        
5    7877     Unknown     1        1        0        0(0%)        0        0        0        0        0        
6    11776    Unknown     2        2        0        0(0%)        0        0        0        0        0        
7    12363    Unknown     1        1        0        0(0%)        0        0        0        0        0        
8    13683    Unknown     2        2        0        0(0%)        0        0        0        0        0        
9    14265    Unknown     1        1        0        0(0%)        0        0        0        0        0        
10   14819    Unknown     1        1        0        0(0%)        0        0        0        0        0        
11   16343    Unknown     1        1        0        0(0%)        0        0        0        0        0        
12   16389    Unknown     1        1        0        0(0%)        0        0        0        0        0        
13   17596    Unknown     2        2        0        0(0%)        0        0        0        0        0        
14   17920    Unknown     2        2        0        0(0%)        0        0        0        0        0        
15   19255    Unknown     1        1        0        0(0%)        0        0        0        0        0        
16   19283    Unknown     2        2        0        0(0%)        0        0        0        0        0        
17   19859    Unknown     1        1        0        0(0%)        0        0        0        0        0        
18   20063    Unknown     1        1        0        0(0%)        0        0        0        0        0        
19   20746    Unknown     1        1        0        0(0%)        0        0        0        0        0        
20   21637    Unknown     1        1        0        0(0%)        0        0        0        0        0        
21   22776    Unknown     1        1        0        0(0%)        0        0        0        0        0        
22   24987    Unknown     1        1        0        0(0%)        0        0        0        0        0        
23   26617    Unknown     1        1        0        0(0%)        0        0        0        0        0        
24   27694    Unknown     1        1        0        0(0%)        0        0        0        0        0        
25   28651    Unknown     1        1        0        0(0%)        0        0        0        0        0        
26   28999    Unknown     1        1        0        0(0%)        0        0        0        0        0        
27   30152    Unknown     3        3        0        0(0%)        0        0        0        0        0        
28   31184    Unknown     5        5        0        0(0%)        0        0        0        0        0        
29   31500    Unknown     1        1        0        0(0%)        0        0        0        0        0        
30   31762    Unknown     2        2        0        0(0%)        0        0        0        0        0        
31   32862    Unknown     1        1        0        0(0%)        0        0        0        0        0        
32   32921    Unknown     1        1        0        0(0%)        0        0        0        0        0        
33   33502    Unknown     1        1        0        0(0%)        0        0        0        0        0        
34   34172    Unknown     1        1        0        0(0%)        0        0        0        0        0        
35   34435    Unknown     1        1        0        0(0%)        0        0        0        0        0        
36   35534    Unknown     4        4        0        0(0%)        0        0        0        0        0        
37   36144    Unknown     4        4        0        0(0%)        0        0        0        0        0        
38   36551    Unknown     2        2        0        0(0%)        0        0        0        0        0        
39   36600    Unknown     1        1        0        0(0%)        0        0        0        0        0        
40   39050    Unknown     3        3        0        1(33%)       0        0        0        0        0        
41   39189    Unknown     2        2        0        0(0%)        0        0        0        0        0        
42   40088    Unknown     5        5        0        0(0%)        0        0        0        0        0        
43   40950    Unknown     2        2        0        0(0%)        0        0        0        0        0        
44   43051    Unknown     3        3        0        0(0%)        0        0        0        0        0        
45   43896    Unknown     1        1        0        0(0%)        0        0        0        0        0        
46   45733    Unknown     3        3        0        0(0%)        0        0        0        0        0        
47   46347    Unknown     3        3        0        0(0%)        0        0        0        0        0        
48   46659    Unknown     1        1        0        0(0%)        0        0        0        0        0        
49   47294    Unknown     1        1        0        0(0%)        0        0        0        0        0        
50   50778    Unknown     1        1        0        0(0%)        0        0        0        0        0        
51   50905    Unknown     1        1        0        0(0%)        0        0        0        0        0        
52   51147    Unknown     1        1        0        0(0%)        0        0        0        0        0        
53   52247    Unknown     1        1        0        0(0%)        0        0        0        0        0        
54   52633    Unknown     1        1        0        0(0%)        0        0        0        0        0        
55   52669    Unknown     4        4        0        0(0%)        0        0        0        0        0        
56   53835    Unknown     1        1        0        0(0%)        0        0        0        0        0        
57   58829    Unknown     1        1        0        1(100%)      0        0        0        0        0        
58   59098    Unknown     2        2        0        0(0%)        0        0        0        0        0        
59   59433    Unknown     1        1        0        0(0%)        0        0        0        0        0        
60   63391    Unknown     2        2        0        0(0%)        0        0        0        0        0        
61   63534    Unknown     1        1        0        0(0%)        0        0        0        0        0        
62   63941    Unknown     1        1        0        0(0%)        0        0        0        0        0        
63   64178    Unknown     1        1        0        0(0%)        0        0        0        0        0        
-------------------------------------------------------------------------------------------------------------
64   3967     Unknown     1        1        0        0(0%)        0        0        1        0        0        
65   4343     Unknown     2        2        0        0(0%)        0        0        1        0        0        
66   36481    Unknown     2        2        0        0(0%)        0        0        1        0        0        
67   36868    Unknown     6        6        0        0(0%)        0        0        1        0        0        
68   42817    Unknown     1        1        0        0(0%)        0        0        1        0        0        
69   45902    Unknown     1        1        0        0(0%)        0        0        1        0        0        
70   48536    Unknown     1        1        0        0(0%)        0        0        1        0        0        
71   52145    Unknown     3        3        0        0(0%)        0        0        1        0        0        
72   57276    Unknown     1        1        0        0(0%)        0        0        1        0        0        
[256Tracking] Total: 0 RNTIs are 64QAM table, 0 RNTIs are 256QAM table, 72 RNTIs are Unknown 

Destroyed Phy
Skipped subframe: 50593 / 278634
nof_decoded_locations, nof_cce, nof_missed_cce, nof_subframes, nof_subframe_collisions_dw, nof_subframe_collisions_up, time, nof_locations
1396305, 102531, 95374, 15733, 6, 0, 0.000000, 173782
Skipped subframes: 50593 (76.3%)
Saving MAC PCAP file
Deleted DL Sniffer core
rifky@rifky-virtual-machine:~/Desktop/LTESniffer/build/src$ ls -ltr
total 79940
-rw-rw-r-- 1 rifky rifky      302 Sep 23 12:27 Settings-Loop-FalconEye.sh
-rwxrwxr-x 1 rifky rifky      951 Sep 23 12:27 set-cpu-governor.sh
-rwxrwxr-x 1 rifky rifky      921 Sep 23 12:27 performance-mode.sh
-rwxrwxr-x 1 rifky rifky     2819 Sep 23 12:27 Loop-FalconEye.sh
-rwxrwxr-x 1 rifky rifky      942 Sep 23 12:27 allow-realtime.sh
-rw-rw-r-- 1 rifky rifky     8747 Sep 23 12:27 Makefile
-rw-rw-r-- 1 rifky rifky     2516 Sep 23 12:27 cmake_install.cmake
drwxrwxr-x 3 rifky rifky     4096 Sep 23 12:27 include
drwxrwxr-x 3 rifky rifky     4096 Sep 23 12:27 CMakeFiles
drwxrwxr-x 3 rifky rifky     4096 Sep 23 12:39 src
-rwxrwxr-x 1 rifky rifky 81784808 Sep 23 12:39 LTESniffer
-rw-r--r-- 1 root  root         0 Sep 23 15:32 ul_sample.raw
-rw-r--r-- 1 root  root     15118 Sep 23 15:37 mcs_statistic.csv
**-rw-r--r-- 1 root  root        24 Sep 23 15:37 ltesniffer_dl_mode.pcap**
-rw-r--r-- 1 root  root        24 Sep 23 15:37 api_collector.pcap

**Comment by hdtuanss** [comment]
Hi, the signal quality in your place is too low (SNR=6db as shown in your log), please place your blade RF outdoor or somewhere with a high SNR. Also, it seems you are using a weak CPU to run LTESniffer, leading to skipping many subframes, please use more powerful CPU.

**Comment by arifkyi** [comment]
Hello Sir,

Thank you very much for your help, you are right, some pcap saved when i moved in some other area still inside my house.

But i will find better strong signal.

Regarding CPU,  would it be help if  currently i use -W 6 , which is six thread, then i will just increase it ?

**Comment by arifkyi** [comment]
Kindly see the config of my VMware, 

feel free to suggest the parameter, maximum 16 core, but i can try 9 core or maximum assign/allocate 12 core?
memory when testing i put it 4 GB, i already increased it to be 8 GB
<img width="868" alt="MemoryCpuConfiguration" src="https://github.com/SysSec-KAIST/LTESniffer/assets/6134601/9f129bcc-d630-4b0e-9ffd-b1107d9332a9">

**Comment by hdtuanss** [comment]
Hi, I recommend you to use a real (physical) machine. Using VM is never a good option to run LTESniffer. Since the USB interface between SDR and VM is not stable, and the CPU is limited. If you still wanna try, I think you should use 12 cores and 8Gb of RAM and see the result again. What is your CPU name?

**Comment by arifkyi** [comment]
Dear Hoang,

You are right Sir.
although as of now i have no luxury to have dedicated machine to install
linux OS,  my host OS is Mac OSX ver 12, if thet possible im so happy 🙏🙏
if LteSniffer have build for MacOS Darwin. anyway i already avoid the
Virtualbox that’s why im using Vmware someone of friends Vmware USB more
stable compare with virtual box.

My host OS is using I9 witj 8 core = 16 logical core, sure i can assign 10
or maybe 12 (i need to try first) and from 16G Ram i will assign 8G ram.

I will try it tommorow and let you know the result 🙏🙏

thanks once again.🙏

**Comment by arifkyi** [comment]
Hello,

appologize, i forgot to close this issue. thanks for your help
