### ISSUE TITLE
Compilation Issue on ARM

### ISSUE THREAD

**Issue by MoPhD** [SysSec-KAIST/LTESniffer#47]
Please see "Make Error at CMakeLists.txt:332 (message):
  no SIMD instructions found" below. 

Is LTESniffer supported on ARM (specifically Apple M2 Pro running Ubuntu 22.04.3 LTS in a VM)?

mo@ubuntu:~/LTESniffer/build$ cmake ../ 
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Build type not specified: defaulting to RelWithDebInfo.
-- CMNALIB LIBRARIES: CMNALIB_LIBRARY-NOTFOUND
-- Could NOT find CMNALIB (missing: CMNALIB_LIBRARIES) 
Download CMNALIB as a subproject and build it.
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mo/LTESniffer/build/cmnalib-download
[ 11%] Performing update step for 'cmnalib'
[ 22%] No patch step for 'cmnalib'
[ 33%] No configure step for 'cmnalib'
[ 44%] No build step for 'cmnalib'
[ 55%] No install step for 'cmnalib'
[ 66%] No test step for 'cmnalib'
[ 77%] Completed 'cmnalib'
[100%] Built target cmnalib
CMake Deprecation Warning at build/cmnalib-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMNALIB_LIBRARY: cmnalib
CMNALIB_LIBRARIES: cmnalib
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (mkl) does
  not match the name of the calling package (MKL).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindMKL.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:115 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find mkl (missing: MKL_LIBRARIES MKL_CORE MKL_ILP MKL_SEQ) 
-- FFTW3F LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
-- FFTW3F STATIC LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.a
-- FFTW3F INCLUDE DIRS: /usr/include
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (fftw3f)
  does not match the name of the calling package (FFTW3F).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindFFTW3F.cmake:41 (find_package_handle_standard_args)
  CMakeLists.txt:121 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- FFT_LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (UHD).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  cmake/modules/FindUHD.cmake:1 (INCLUDE)
  CMakeLists.txt:137 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- UHD LIBRARIES /usr/local/lib/libuhd.so
-- UHD INCLUDE DIRS /usr/local/include
-- Checking for module 'libbladeRF'
--   No package 'libbladeRF' found
-- libbladeRF not found.
-- FINDING SOAPY.
-- Checking for module 'SoapySDR'
--   No package 'SoapySDR' found
-- libSOAPYSDR not found.
CMake Warning at CMakeLists.txt:170 (find_package):
  By not providing "FindSRSRAN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SRSRAN", but
  CMake did not find one.

  Could not find a package configuration file provided by "SRSRAN" with any
  of the following names:

    SRSRANConfig.cmake
    srsran-config.cmake

  Add the installation prefix of "SRSRAN" to CMAKE_PREFIX_PATH or set
  "SRSRAN_DIR" to a directory containing one of the above files.  If "SRSRAN"
  provides a separate development package or SDK, be sure it has been
  installed.

Download SRSRAN as a subproject and build it.
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mo/LTESniffer/build/srsRAN-download
[ 11%] Performing update step for 'srsRAN'
HEAD is now at 9d6781c Update refsignal_ul.c
[ 22%] No patch step for 'srsRAN'
[ 33%] No configure step for 'srsRAN'
[ 44%] No build step for 'srsRAN'
[ 55%] No install step for 'srsRAN'
[ 66%] No test step for 'srsRAN'
[ 77%] Completed 'srsRAN'
[100%] Built target srsRAN
CMake Deprecation Warning at build/srsRAN-src/CMakeLists.txt:33 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- CMAKE_SYSTEM: Linux-5.15.0-91-generic
-- CMAKE_SYSTEM_PROCESSOR: aarch64
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- Detected aarch64 processor
-- FFTW3F LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
-- FFTW3F STATIC LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.a
-- FFTW3F INCLUDE DIRS: /usr/include
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (fftw3f)
  does not match the name of the calling package (FFTW3F).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindFFTW3F.cmake:41 (find_package_handle_standard_args)
  build/srsRAN-src/CMakeLists.txt:168 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- FFT_LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
-- Checking for module 'polarssl'
--   No package 'polarssl' found
-- POLARSSL LIBRARIES: POLARSSL_LIBRARIES-NOTFOUND
-- POLARSSL STATIC LIBRARIES: POLARSSL_STATIC_LIBRARIES-NOTFOUND
-- POLARSSL INCLUDE DIRS: POLARSSL_INCLUDE_DIRS-NOTFOUND
-- Could NOT find Polarssl (missing: POLARSSL_LIBRARIES POLARSSL_INCLUDE_DIRS) 
-- Checking for module 'mbedtls'
--   No package 'mbedtls' found
-- MBEDTLS LIBRARIES: /usr/lib/aarch64-linux-gnu/libmbedcrypto.so
-- MBEDTLS STATIC LIBRARIES: /usr/lib/aarch64-linux-gnu/libmbedcrypto.a
-- MBEDTLS INCLUDE DIRS: /usr/include
-- Checking for module 'libpcsclite'
--   No package 'libpcsclite' found
-- Could NOT find PCSCLite (missing: PCSCLITE_LIBRARY PCSCLITE_INCLUDE_DIR) 
-- PCSC LIBRARIES: PCSCLITE_LIBRARY-NOTFOUND
-- PCSC INCLUDE DIRS: PCSCLITE_INCLUDE_DIR-NOTFOUND
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (UHD).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  cmake/modules/FindUHD.cmake:1 (INCLUDE)
  build/srsRAN-src/CMakeLists.txt:220 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (SKIQ).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  build/srsRAN-src/cmake/modules/FindSKIQ.cmake:21 (INCLUDE)
  build/srsRAN-src/CMakeLists.txt:229 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- SKIQ LIBRARIES SKIQ_LIBRARY-NOTFOUND/usr/lib/aarch64-linux-gnu/libglib-2.0.a/usr/lib/aarch64-linux-gnu/libusb-1.0.a
-- SKIQ INCLUDE DIRS SKIQ_INCLUDE_DIRS-NOTFOUND
-- Could NOT find SKIQ (missing: SKIQ_INCLUDE_DIRS) 
-- Checking for module 'libbladeRF'
--   No package 'libbladeRF' found
-- libbladeRF not found.
-- FINDING SOAPY.
-- Checking for module 'SoapySDR'
--   No package 'SoapySDR' found
-- libSOAPYSDR not found.
-- FINDING ZEROMQ.
-- Checking for module 'ZeroMQ'
--   No package 'ZeroMQ' found
-- libZEROMQ not found.
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.35") found components: program_options 
-- SRSGUI LIBRARIES /usr/local/lib/libsrsgui.so
-- SRSGUI INCLUDE DIRS /usr/local/include
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR) 
-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR) 
-- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR) 
-- Backward-cpp found, but external libraries are missing.
-- Detected ARM processor
-- CMAKE_C_FLAGS is  -Wno-unused-but-set-variable -Wall -Wno-comment -Wno-write-strings -Wno-unused-result -Wformat -Wmissing-field-initializers -Wtype-limits -std=c99 -fno-strict-aliasing -D_GNU_SOURCE -ggdb -DBUILD_TYPE_RELWITHDEBINFO -DIS_ARM -DHAVE_NEON -DHAVE_NEONv8 -fvisibility=hidden -Werror --param large-function-growth=1600
-- CMAKE_CXX_FLAGS is  -Wall -Wno-comment -Wno-reorder -Wno-unused-variable -Wtype-limits -std=c++11 -fno-strict-aliasing -Wno-unused-but-set-variable -ggdb -DBUILD_TYPE_RELWITHDEBINFO -DIS_ARM -DHAVE_NEONv8 -Werror
-- Using install prefix: /usr/local
-- Building for version: 21.10.0
--    examples will be installed.
-- Checking for module 'sctp'
--   No package 'sctp' found
-- SCTP LIBRARIES: /usr/lib/aarch64-linux-gnu/libsctp.so
-- SCTP INCLUDE DIRS: /usr/include
-- No post-build command defined
-- No post-build command defined
-- Building with srsUE
-- No post-build command defined
-- No post-build command defined
-- No post-build-UE command defined
-- Building with srsENB
-- Found LibConfig++: /usr/lib/aarch64-linux-gnu/libconfig++.so
-- static LibConfig++ path: /usr/lib/aarch64-linux-gnu/libconfig++.a
-- Found LibConfig: /usr/lib/aarch64-linux-gnu/libconfig.so
-- static LibConfig path: /usr/lib/aarch64-linux-gnu/libconfig.a
-- Checking for module 'sctp'
--   No package 'sctp' found
-- SCTP LIBRARIES: /usr/lib/aarch64-linux-gnu/libsctp.so
-- SCTP INCLUDE DIRS: /usr/include
-- No post-build-ENB command defined
-- Building with srsEPC
-- Found LibConfig++: /usr/lib/aarch64-linux-gnu/libconfig++.so
-- static LibConfig++ path: /usr/lib/aarch64-linux-gnu/libconfig++.a
-- Found LibConfig: /usr/lib/aarch64-linux-gnu/libconfig.so
-- static LibConfig path: /usr/lib/aarch64-linux-gnu/libconfig.a
-- Checking for module 'sctp'
--   No package 'sctp' found
-- SCTP LIBRARIES: /usr/lib/aarch64-linux-gnu/libsctp.so
-- SCTP INCLUDE DIRS: /usr/include
-- No post-build-EPC command defined
SRSRAN_LIBRARIES: srsran_commonsrsran_physrsran_asn1srsran_gtpusrsran_macsrsran_pdcpsrsran_rlcsrsran_rfsrsran_radio
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.35") found components: program_options system thread 
MARCH - FLAGS: native
CMake Error at CMakeLists.txt:332 (message):
  no SIMD instructions found

-- Configuring incomplete, errors occurred!
See also "/home/mo/LTESniffer/build/CMakeFiles/CMakeOutput.log".
See also "/home/mo/LTESniffer/build/CMakeFiles/CMakeError.log".

**Comment by hdtuanss** [comment]
Hi, 
It seems the SIMD instructions technique on Apple CPU is not compatible with LTESniffer. This SIMD, which is often supported in Intel CPUs, is used to accelerate the turbo decoder of LTESniffer and srsRAN lib. 
Could you build LTESniffer on an Ubuntu + Intel CPU machine?
Thanks.

**Comment by hdtuanss** [comment]
> @MoPhD I saw this post a couple days ago and just now by chance saw [this CMake option](https://github.com/SysSec-KAIST/LTESniffer/blob/main/CMakeLists.txt#L22) that looks like it might solve your issue.
> 
> When running your command `cmake ..`, add an additional flag like so:
> 
> ```
> cmake .. -DDISABLE_SIMD=on
> ```

Thanks for your answer.

@MoPhD Could you try this way?

**Comment by MoPhD** [comment]
Thank you for the responses, running using cmake .. -DDISABLE_SIMD=on appears to resolve the error.
