### ISSUE TITLE
uninstall project / undo installation of drivers

### ISSUE THREAD

**Issue by SeaQuench** [SysSec-KAIST/LTESniffer#53]
hello, i appreciate the effort behind this project; however, i need to revert the behavior of the UHD for use on other projects. can you advise me how to uninstall or remove any UHD code (e.g. driver) that was installed via `sudo make install`? i did not see an uninstall option in the makefile. perhaps i should have installed this in a VM.

**Comment by hdtuanss** [comment]
Hi, in the build directory of UHD, you can do ``sudo make uninstall`` to uninstall UHD. Then, you should do ``sudo ldconfig`` to apply changes to system. After that, you can install new UHD version. Dont forget to re-build your project once you make change in UHD version.
Thanks
