### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by MoPhD** [SysSec-KAIST/LTESniffer#63]
Hello,

I am receiving the following error message numerous times when running LTESniffer:

/home/me/LTESniffer/build/srsRAN-src/lib/src/phy/phch/ra_dl.c:199: Invalid RBG subset=3 for nof_prb=50 where P=3

Please advise if this can be ignored as the program does appear to function, although I am still in the early stages of understanding it well.

Thanks.

**Comment by hdtuanss** [comment]
Hi, 
Could you please check the downlink SNR in your location?
You can run LTESniffer in the downlink sniffing mode with option -d to print out SNR.
I usually have these error messages when the signal quality is bad (Low SNR).
Thanks
