### ISSUE TITLE
Error receiving samples??

### ISSUE THREAD

**Issue by stuitee** [SysSec-KAIST/LTESniffer#75]
INFO] [UHD] linux; GNU C++ version 11.4.0; Boost_107400; UHD_4.1.0.HEAD-0-gd21735d5
[INFO] [LOGGING] Fastpath logging disabled at runtime.
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
 - Type:            FDD
 - PCI:             364
 - Nof ports:       4
 - CP:              Normal  
 - PRB:             100
 - PHICH Length:    Normal
 - PHICH Resources: 1
 - SFN:             884
Decoded MIB. SFN: 884, offset: 1

/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()
/home/jjw/workarea/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/jjw/LTESniffer-main/build/srsRAN-src/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/jjw/LTESniffer-main/src/src/LTESniffer_Core.cc:370: Error calling srsran_ue_sync_work()

**Comment by hdtuanss** [comment]
Hi, you are listening on a 4-port eNB, which is not supported by LTESniffer, only 1-port and 2-port eNB are supported. Thanks
