### ISSUE TITLE
Please add support on bladerf micro ax4 to uplink

### ISSUE THREAD

**Issue by marcosi2** [SysSec-KAIST/LTESniffer#76]
Please make support so that the bladerf micro ax4 can decode uplink see what an impressive configuration this tool has.

The bladeRF 2.0 micro xA4 THERMAL is the next generation Software Defined Radio (SDR) offering a frequency range of 47MHz to 6GHz, 61.44MHz sampling rate ([capable of up to 122.88MHz](https://www.nuand.com/2023-02-release-122-88mhz-bandwidth/)), and 2×2 MIMO streaming. Packed into a small form factor, the bladeRF 2.0 micro was designed for high performance as well as mobile applications. Through libbladeRF the bladeRF 2.0 micro is compatible with GNURadio, GQRX, SDR-Radio, SDR#, gr-fosphor, SoapySDR, and more on Windows, Linux and macOS.

**Comment by hdtuanss** [comment]
Hi, unfortunately, we dont have any plan to support bladerf for uplink sniffing.
I appreciate it if you could develop and contribute your code to LTESniffer. 
Thank you!
