### ISSUE TITLE
Does it support 4G network?

### ISSUE THREAD

**Issue by lee-cq** [SysSec-KAIST/LTESniffer#77]
I would like to inquire about the software's support for 4G signal. 
Can I utilize this software to decode communication data between 4G base stations and devices? 
Presently, I am in need of testing whether there are any security concerns regarding the entire outbound traffic from my 4G device.

**Comment by hdtuanss** [comment]
Hi, LTE is another term for 4G. Yes, LTESniffer does support 4G.
Thank you!
