### ISSUE TITLE
There is no MIB information in the ltesniffer_dl_mode.pcap file

### ISSUE THREAD

**Issue by ZoroBryant** [SysSec-KAIST/LTESniffer#85]
I parsed the ltesniffer_dl_mode.pcap file file and could not find the MIB information in it.
The ltesniffer_dl_mode.pcap file generated by LTESniffer does not contain MIB information?

**Comment by hdtuanss** [comment]
Hi, MIB is not saved to pcap file, please print it out during the cell search procedure.
Also, as far as I know, wireshark does not support mib. Please correct me if I;m wrong.
Thank you!
