### ISSUE TITLE
Update link to CellularZ in the readme file

### ISSUE THREAD

**Issue by rsalmond** [SysSec-KAIST/LTESniffer#87]
The [current link](https://github.com/SysSec-KAIST/LTESniffer/blob/main/README.md?plain=1#L276) in the doc is 404ing. [This](https://play.google.com/store/apps/details?id=make.more.r2d2.cellular_z.play) appears to be the updated link.

**Comment by hdtuanss** [comment]
Hi, the new link is updated. Thank you for reminding me!
